config/routes.rb
MdmStandart::Application.routes.draw do

  get "settings/edit"

  mount Ckeditor::Engine => '/ckeditor'

  scope module: :web do
    root to: "welcome#index"

    resources :pages, only: [ :show ]
    resource :session, only: [ :new, :create, :destroy ]
    resources :questions, only: [ :new, :create ]
    resource :measure, only: [:new, :create]
    resources :news, only: [:show]

    namespace :admin do
      root to: "welcome#index"

      resources :menus
      resources :products
      resources :users
      resources :pages
      resources :news
      resources :measures
      resources :feedbacks
      resources :questions

      resource :settings, only: [:edit, :update]
    end
  end
end

app/models/call_measurer.rb
class CallMeasurer < ActiveRecord::Base
  include CallMeasurerRepository
  attr_accessible :contacts, :content, :full_name

  validates :full_name, presence: true, length: { maximum: 255 }
  validates :contacts, presence: true, length: { maximum: 255 }

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  include MenuRepository

  attr_accessible :slug, :title
  has_many :items, class_name: 'Menu::Item'
  has_many :pages

  validates :title, presence: true, length: { maximum: 255 }
  validates :slug, presence: true, length: { maximum: 255 }, slug: true

end

app/models/menu/item.rb
class Menu::Item < ActiveRecord::Base
  attr_accessible :menu_id, :position, :slug, :title

  belongs_to :menu

  validates :title, presence: true, length: { maximum: 255 }
  validates :slug, presence: true, length: { maximum: 255 }
  validates :position, presence: true

  def to_s
    title
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  include NewsRepository

  attr_accessible :content, :preview_image, :title

  mount_uploader :preview_image, NewsPreviewImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true

  state_machine initial: :inactive do
    state :inactive
    state :active
    state :trashed

    event :activate do
      transition [:inactive, :trashed] => :active
    end

    event :deactivate do
      transition [:active, :trashed] => :inactive
    end

    event :trash do
      transition [:active, :inactive] => :trashed
    end
  end

  def to_s
    title
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
  include PageRepository

  belongs_to :menu

  attr_accessible :content, :slug, :title
  validates :title, presence: true, length: { maximum: 255 }
  validates :slug, presence: true, slug: true, length: { maximum: 255 }

  state_machine initial: :inactive do
    state :inactive
    state :active
    state :trashed

    event :activate do
      transition [:inactive, :trashed] => :active
    end

    event :deactivate do
      transition [:active, :trashed] => :inactive
    end

    event :trash do
      transition [:active, :inactive] => :trashed
    end
  end

  def to_s
    title
  end

  def to_param
    slug
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  include ProductRepository

  attr_accessible :preview_image, :title, :size, :options

  has_many :profiles, class_name: 'Product::Profile', dependent: :destroy

  validates :title, presence: true, length:  { maximum: 255 }
  validates :size, presence: true, length:  { maximum: 255 }
  validates :options, presence: true, length:  { maximum: 255 }

  mount_uploader :preview_image, ProductPreviewUploader

  state_machine initial: :inactive do
    state :inactive
    state :active
    state :trashed

    event :activate do
      transition [:inactive, :trashed] => :active
    end

    event :deactivate do
      transition [:active, :trashed] => :inactive
    end

    event :trash do
      transition [:active, :inactive] => :trashed
    end
  end

  def to_s
    title
  end
end

app/models/product/profile.rb
class Product::Profile < ActiveRecord::Base
  include UsefullScopes
  attr_accessible :brick_house_cost, :panel_house_cost, :product_id, :title

  belongs_to :product

  validates :title, presence: true, length: { maximum: 255 }

  def to_s
    title
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include QuestionRepository

  attr_accessible :content, :email, :full_name, :phone

  validates :full_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 }, email: true
  validates :phone, presence: true, length: { maximum: 255 }
  validates :content, presence: true

  def to_s
    full_name
  end
end

app/models/site_settings.rb
class SiteSettings < ActiveRecord::Base
  attr_accessible :banner, :show_banner, :banner_link

  mount_uploader :banner, SiteSettingsUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  include UserRepository

  has_secure_password
  attr_accessible :email, :password

  validates :email, presence: true, email: true, length: { maximum: 255 }
  validates :password, length: { maximum: 255 }

  state_machine initial: :inactive do
    state :inactive
    state :active

    event :activate do
      transition :inactive => :active
    end

    event :deactivate do
      transition :active => :inactive
    end
  end

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/web/admin/products_controller.rb
class Web::Admin::ProductsController < Web::Admin::ApplicationController
  def index
    @search = Product.ransack params[:q]
    @items = @search.result.page(params[:page]).per(20)
  end

  def new
    @item = ::Web::Admin::ProductEditType.new
  end

  def create
    @item = ::Web::Admin::ProductEditType.new params[:product]
    if @item.save
      flash_success
      redirect_to edit_admin_product_path(@item)
    else
      flash_error
      render :new
    end
  end

  def edit
    @item = ::Web::Admin::ProductEditType.find params[:id]
  end

  def update
    @item = ::Web::Admin::ProductEditType.find params[:id]
    if @item.update_attributes params[:product]
      flash_success
      redirect_to edit_admin_product_path(@item)
    else
      flash_error
      render :edit
    end
  end

  def destroy
    @item = Product.find params[:id]
    @item.destroy
    flash_success
    redirect_to admin_products_path
  end
end

app/controllers/web/news_controller.rb
class Web::NewsController < Web::ApplicationController
  def show
    @item = News.find params[:id]
  end
end

app/controllers/web/pages_controller.rb
class Web::PagesController < Web::ApplicationController
  def show
    @page = Page.find_by_slug! params[:id]
  end
end

app/helpers/api/application_helper.rb
module Api::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_submenu(menu)
    items = menu.items.each_slice(3)
    render 'web/shared/submenu', items: items
  end

  def news_items
    @news ||= News.web
  end

  def products_items
    @products ||= Product.web
  end

  def settings(key)
    @settings ||= SiteSettings.first
    @settings.send(key)
  end
end

app/helpers/web/admin/products_helper.rb
module Web::Admin::ProductsHelper
end

app/helpers/web/application_helper.rb
module Web::ApplicationHelper
end

app/helpers/web/measures_helper.rb
module Web::MeasuresHelper
end

app/helpers/web/news_helper.rb
module Web::NewsHelper
end

app/helpers/web/questions_helper.rb
module Web::QuestionsHelper
end

app/views/web/admin/products/_form.html.haml
= simple_form_for [:admin, @item] do |f|
  = f.input :state_event, as: :state_event
  = f.input :title
  = f.input :size
  = f.input :options
  = f.input :preview_image, as: :image_preview

  %h4 Профили
  #items
    = f.simple_fields_for :profiles do |item|
      = render 'profile_fields', f: item

  = link_to_add_association 'Добавить профиль', f, :profiles, class: 'btn btn-info',
     data: { association_insertion_node: '#items', association_insertion_method: 'append' }


  = f.submit class: 'btn btn-primary'

app/views/web/admin/products/_profile_fields.html.haml
.nested-fields.well
  .row
    .span3
      = f.input :title, label: false, input_html: { placeholder: Product::Profile.human_attribute_name(:title) }
    .span3
      = f.input :brick_house_cost, label: false, input_html: { placeholder: Product::Profile.human_attribute_name(:brick_house_cost) }
    .span3
      = f.input :panel_house_cost, label: false, input_html: { placeholder: Product::Profile.human_attribute_name(:panel_house_cost) }
    .span3
      = link_to_remove_association "Удалить профиль", f, class: 'btn btn-danger'

app/views/web/admin/products/edit.html.haml
%h1= t '.title'

= render 'form'

app/views/web/admin/products/index.html.haml
.page-header
  %h1=t('.title')
  
= simple_form_for @search, url: admin_products_path, method: :get do |f|
  %table.table
    %thead
      %tr
        %td
          = f.input_field :title_cont, placeholder: Product.human_attribute_name(:title), label: false, required: false
        %td
          = f.input_field :size_cont, placeholder: Product.human_attribute_name(:size), label: false, required: false
        %td
          = f.input_field :options_cont, placeholder: Product.human_attribute_name(:options), label: false, required: false
        %td
          = f.input :state_in, collection: Product.state_machine.states.map { |s| [s.human_name, s.name] }, input_html: { data: { placeholder: Product.human_attribute_name(:state) }}, label: false, required: false

        %td
          = f.submit t(".search"), :class => 'btn btn-primary' 

= link_to t('.new'), new_admin_product_path, class: 'btn btn-primary'
    
= paginate @items
%table.table.table-striped
  %thead
    %tr
      %th= sort_link(@search, :id, Product.human_attribute_name(:id))
      %th= sort_link(@search, :title, Product.human_attribute_name(:title))
      %th= sort_link(@search, :size, Product.human_attribute_name(:size))
      %th= sort_link(@search, :state, Product.human_attribute_name(:state))
      %th= sort_link(@search, :created_at, Product.human_attribute_name(:created_at))
      %th= t(".actions")
  %tbody
    - @items.each do |item|
      %tr
        %td= link_to item.id, edit_admin_product_path(item)
        %td= item.title
        %td= item.size
        %td= item.human_state_name
        %td= l item.created_at
        %td
          = link_to t('.edit'), [:edit, :admin, item], class: 'btn btn-mini'
          = link_to t('.destroy'), [:admin, item], method: :delete, data: { confirm: t('.confirm') }, class: 'btn btn-mini btn-danger'
= paginate @items

= link_to t('.new'), new_admin_product_path, class: 'btn btn-primary'

app/views/web/admin/products/new.html.haml
%h1= t '.title'

= render 'form'