config/routes.rb
MdmStandart::Application.routes.draw do

  get "settings/edit"

  mount Ckeditor::Engine => '/ckeditor'

  scope module: :web do
    root to: "welcome#index"

    resources :pages, only: [ :show ]
    resource :session, only: [ :new, :create, :destroy ]
    resources :questions, only: [ :new, :create ]
    resource :measure, only: [:new, :create]
    resources :news, only: [:show]

    namespace :admin do
      root to: "welcome#index"

      resources :menus
      resources :products
      resources :users
      resources :pages
      resources :news
      resources :measures
      resources :feedbacks
      resources :questions

      resource :settings, only: [:edit, :update]
    end
  end
end

app/models/call_measurer.rb
class CallMeasurer < ActiveRecord::Base
  include CallMeasurerRepository
  attr_accessible :contacts, :content, :full_name

  validates :full_name, presence: true, length: { maximum: 255 }
  validates :contacts, presence: true, length: { maximum: 255 }

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  include MenuRepository

  attr_accessible :slug, :title
  has_many :items, class_name: 'Menu::Item'
  has_many :pages

  validates :title, presence: true, length: { maximum: 255 }
  validates :slug, presence: true, length: { maximum: 255 }, slug: true

end

app/models/menu/item.rb
class Menu::Item < ActiveRecord::Base
  attr_accessible :menu_id, :position, :slug, :title

  belongs_to :menu

  validates :title, presence: true, length: { maximum: 255 }
  validates :slug, presence: true, length: { maximum: 255 }
  validates :position, presence: true

  def to_s
    title
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  include NewsRepository

  attr_accessible :content, :preview_image, :title

  mount_uploader :preview_image, NewsPreviewImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true

  state_machine initial: :inactive do
    state :inactive
    state :active
    state :trashed

    event :activate do
      transition [:inactive, :trashed] => :active
    end

    event :deactivate do
      transition [:active, :trashed] => :inactive
    end

    event :trash do
      transition [:active, :inactive] => :trashed
    end
  end

  def to_s
    title
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
  include PageRepository

  belongs_to :menu

  attr_accessible :content, :slug, :title
  validates :title, presence: true, length: { maximum: 255 }
  validates :slug, presence: true, slug: true, length: { maximum: 255 }

  state_machine initial: :inactive do
    state :inactive
    state :active
    state :trashed

    event :activate do
      transition [:inactive, :trashed] => :active
    end

    event :deactivate do
      transition [:active, :trashed] => :inactive
    end

    event :trash do
      transition [:active, :inactive] => :trashed
    end
  end

  def to_s
    title
  end

  def to_param
    slug
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  include ProductRepository

  attr_accessible :preview_image, :title, :size, :options

  has_many :profiles, class_name: 'Product::Profile', dependent: :destroy

  validates :title, presence: true, length:  { maximum: 255 }
  validates :size, presence: true, length:  { maximum: 255 }
  validates :options, presence: true, length:  { maximum: 255 }

  mount_uploader :preview_image, ProductPreviewUploader

  state_machine initial: :inactive do
    state :inactive
    state :active
    state :trashed

    event :activate do
      transition [:inactive, :trashed] => :active
    end

    event :deactivate do
      transition [:active, :trashed] => :inactive
    end

    event :trash do
      transition [:active, :inactive] => :trashed
    end
  end

  def to_s
    title
  end
end

app/models/product/profile.rb
class Product::Profile < ActiveRecord::Base
  include UsefullScopes
  attr_accessible :brick_house_cost, :panel_house_cost, :product_id, :title

  belongs_to :product

  validates :title, presence: true, length: { maximum: 255 }

  def to_s
    title
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include QuestionRepository

  attr_accessible :content, :email, :full_name, :phone

  validates :full_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 }, email: true
  validates :phone, presence: true, length: { maximum: 255 }
  validates :content, presence: true

  def to_s
    full_name
  end
end

app/models/site_settings.rb
class SiteSettings < ActiveRecord::Base
  attr_accessible :banner, :show_banner, :banner_link

  mount_uploader :banner, SiteSettingsUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  include UserRepository

  has_secure_password
  attr_accessible :email, :password

  validates :email, presence: true, email: true, length: { maximum: 255 }
  validates :password, length: { maximum: 255 }

  state_machine initial: :inactive do
    state :inactive
    state :active

    event :activate do
      transition :inactive => :active
    end

    event :deactivate do
      transition :active => :inactive
    end
  end

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/web/news_controller.rb
class Web::NewsController < Web::ApplicationController
  def show
    @item = News.find params[:id]
  end
end

app/helpers/api/application_helper.rb
module Api::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_submenu(menu)
    items = menu.items.each_slice(3)
    render 'web/shared/submenu', items: items
  end

  def news_items
    @news ||= News.web
  end

  def products_items
    @products ||= Product.web
  end

  def settings(key)
    @settings ||= SiteSettings.first
    @settings.send(key)
  end
end

app/helpers/web/application_helper.rb
module Web::ApplicationHelper
end

app/helpers/web/measures_helper.rb
module Web::MeasuresHelper
end

app/helpers/web/news_helper.rb
module Web::NewsHelper
end

app/helpers/web/questions_helper.rb
module Web::QuestionsHelper
end

app/views/layouts/shared/web/_companies.html.haml
.container.companies
  .row
    .span5.offset1
      = link_to 'http://mdm-group.ru/', class: 'company-link' do
        %i.mdm-group
    .span5
      = link_to 'http://www.cryspi.ru/', class: 'company-link' do
        %i.cryspi
  .row
    .span5.offset1
      = link_to 'http://www.indexeventus.ru/', class: 'company-link' do
        %i.indexeventus
    .span5
      = link_to 'http://po-vitrina.ru/', class: 'company-link' do
        %i.vitrina

app/views/layouts/shared/web/_footer_company.html.haml
%footer.footer_company
  .container-fluid
    .row
      .span5
        %p “Окна вашего дома” #{Time.current.year} - все права защищены

app/views/layouts/shared/web/_header.html.haml
.container-fluid
  .row-fluid.custom-header
    .span2
      .left-btns
        .rule
          = link_to 'Вызвать замерщика', new_measure_path, class: 'measure-btn'
        -#= link_to '', "/consult/", class: 'consult-btn'

    .span4.logo-box
      = link_to '', root_path, class: 'logo-btn'

    .span4.logo-box
      - if settings :show_banner
        %a{ href: settings(:banner_link) }
          %img.banner-btn(src="#{settings(:banner_url)}")

    .span2.right
      .right-text
        .fast-consult-label Мы работаем с 9:00 до 18:00
        .phone 75-84-71, 70-38-71
        = link_to 'Заказать обратный звонок!', new_question_path, class: 'feedback-call-btn clearfix'
        %a.email-btn(href="mailto:info@oknavd.ru")
          %i.icon-envelope
          info@oknavd.ru

app/views/layouts/shared/web/_navbar.html.haml
.container.custom-top-menu-container
  .navbar.custom-top-menu
    .navbar-inner
      .container
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to '', root_path, class: 'brand'
        %ul.nav.nav-collapse
          %li= link_to "Окна и двери", page_path(:product)
          %li= link_to "Услуги", page_path(:services)
          %li= link_to "Преимущества окон ПВХ", page_path(:advantages)
          %li= link_to "О компании", page_path(:company)
          -#%li= link_to "Где купить", page_path(:offices)
          %li= link_to "Контакты", page_path(:contacts)

app/views/layouts/shared/web/_news.html.haml
%h3.header Новости
.content
  - news_items.each do |n|
    .news-block
      -# %img{ src: n.preview_image_url }
      = link_to n.title, news_path(n)

app/views/layouts/shared/web/_price.html.haml
.content
  %h3 Прайс-лист

  .items
    - products_items.each do |p|
      .item.well.well-small
        .row
          .span2.image
            - if p.preview_image.url
              = image_tag p.preview_image.url
          .span6.item-content
            %h5 #{p.title}, #{p.size}, #{p.options}

            %table.table.table-striped
              %thead
                %tr
                  %th Профиль
                  %th Панельный дом
                  %th Кирпичный дом

              %tbody
                - p.profiles.asc_by_created_at.each do |profile|
                  %tr
                    %td= profile.title
                    %td= profile.panel_house_cost
                    %td= profile.brick_house_cost

app/views/layouts/web/admin/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Панель администратора | МДМ Стандарт"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "admin", :media => "all"
    %link(href="favicon.ico" rel="shortcut icon")

  %body
    .navbar.navbar-fixed-top.navbar-inverse
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          -#= link_to "Окна Вашего Дома", admin_root_path, class: :brand
          .nav-collapse
            %ul.nav
              %li= link_to "Прайс-лист", admin_products_path
              %li= link_to "Пользователи", admin_users_path
              %li= link_to "Страницы", admin_pages_path
              %li= link_to "Меню", admin_menus_path
              %li= link_to "Новости", admin_news_index_path
              %li= link_to "Вызовы замерщика", admin_measures_path
              %li= link_to "Обратная связь", admin_questions_path
              %li= link_to "Настройки", edit_admin_settings_path

          %ul.nav.pull-right.nav-collapse
            %li.divider-vertical
            %li.dropdown
              %a.dropdown-toggle(href="#" data-toggle="dropdown")
                = current_user.email
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Профиль", edit_admin_user_path(current_user)
                %li= link_to "Выход", session_path, method: :delete
    .container
      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Меню
            %ul.nav.nav-list
              %li= link_to "На сайт", root_path
              %li= link_to "Настройки сайта", edit_admin_settings_path
              %li= link_to "Пользователи", admin_users_path
              %li= link_to "Меню", admin_menus_path
              %li= link_to "Страницы", admin_pages_path
              %li= link_to "Новости", admin_news_index_path
              %li= link_to "Вызовы замерщика", admin_measures_path
              %li= link_to "Обратная связь", admin_questions_path

      %br
      %br
      %br
      %footer
        %p &copy; Alexey Frank 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "admin"

app/views/web/pages/show.html.haml
- if @page.menu
  = render_submenu @page.menu

.page-header
  %h1= @page
= @page.content.html_safe if @page.content

app/views/web/shared/_submenu.html.haml
.submenu.row
  = items.each do |chunk|
    .span3
      %ul
        - chunk.each do |item|
          %li= link_to item, item.slug